### ISSUE TITLE
How to approach versioning for Notion 4

### ISSUE THREAD

**Issue by raboof** [raboof/notion#121]
I'd like to discuss how we should approach versioning for Notion 4.

In general I think 'releasing' is a bit of an antiquated concept: any commit on `master` should be suitable for production. So I think we have 2 options:

* Each commit on master is 'automatically' a release
* Releasing is a low-friction event that requires tagging a commit on master (but not more)

When releasing by tagging a commit, the version can simply be the tag. When releasing 'any' commit on master, we would have to determine the version number by something like 'git describe'. I don't want to include the version number inside the repo, because that might cause multiple commits to accidentally be assigned the same version number.

It would be nice to have 'reproducible builds' in the sense that checking out a release and building it with the same settings should produce a binary with the same bytes. Ideally this would work when checking out a github tag as well as downloading the tag zip from the GitHub UI. Since when downloading the tag zip from the GitHub we don't have access to the git history, 'git describe' will not work.

This points in the direction of releasing-by-tagging.

This is simple enough. The question remains how to name the releases. Options:

* Current scheme: `4-2019062000`
* Triplet: `4.0.0`
* Tuple: `4.0`

The advantage of the current scheme is that the release date is visible from the version. The disadvantage is also that the release date is visible from the version ;), plus it looks a bit foreign.

The advantage of the triplet approach is that it looks familiar. The disadvantage is that it looks a bit like SemVer, but SemVer doesn't really make sense for a non-library project like Notion. We could of course have a informal 'minor version for large changes, patch version for small changes' convention, but it's still a bit awkward.

The advantage of the tuplet approach is we won't have to distinguish between 'large' and 'small' changes anymore, but the minor version will grow quickly.

What do you think?

**Comment by wilhelmy** [comment]
I'd say either the current scheme or tuple, introducing a patch level into the version number doesn't really make sense...

systemd introduced the convention of having a single version number that's just incremented with each release, so in theory that would be a fourth option.

Other than that it looks a bit unusual, I don't see any drawbacks of the current scheme. Being able to see the release date is a good motivation to discourage slacking ;)

**Comment by wilhelmy** [comment]
Apparently archlinux didn't get the memo that 3 is part of the version number:
https://git.archlinux.org/svntogit/community.git/tree/trunk/PKGBUILD?h=packages/notion

**Comment by knixeur** [comment]
I prefer tagging to release.
And regarding versioning, I'd go with tuple, one number would increment quickly and would be kind of confusing to note that there's something major released. I have used dates on some projects before people tend to get confused due to the "gigh numbers", aaand sometimes you've to publish a quick fix the same day :laughing:

**Comment by raboof** [comment]
Current votes:

Procedure:
* automatic releases: 1 (raboof)
* tagged releases: 2 (knixeur, wilhelmy)

* `4.x.y`: 2 (knixeur, raboof)
* `4.x`: 1 (wilhelmy)
* `4-2019082700`: 1 (wilhelmy)

So this would have us land on "manual releases of the form 4.x.y". I'll leave this open for a while so further participants can chime in ;).

**Comment by wilhelmy** [comment]
Let's not turn this into a bikeshed issue. 4.x.y is fine, too. ;)

**Comment by raboof** [comment]
"manual releases of the form 4.x.y" it is! :tada:
