### ISSUE TITLE
Ensure that lua 5.3 is supported

### ISSUE THREAD

**Issue by wilhelmy** [raboof/notion#124]
/usr/local/bin/notion: ioncore_misc.lua:77: attempt to call a nil value (global 'unpack')

It seems the unpack() function was removed. Maybe there's more.

**Comment by wilhelmy** [comment]
Some wisdom from the internet: "In Lua 5.2, unpack was moved to table.unpack."

So I guess sprinkling about some `local unpack = unpack or table.unpack` should do the trick.

I might look into it.

**Comment by wilhelmy** [comment]
I think that wasn't it.

https://www.lua.org/pil/5.2.html

unpack() in this case is used to unpack "arg", I think they changed the way variable arguments work in Lua 5.3. Since "arg" on the global level is also what argv is in C, this introduces additional confusion — I've seen command line arguments show up in unexpected places.

**Comment by wilhelmy** [comment]
```
Lua 5.3.5  Copyright (C) 1994-2018 Lua.org, PUC-Rio
> function foo(...)
>> return arg
>> end
> foo(1,2,3)
table: 0x5579dc40b430
> foo(1)
table: 0x5579dc40b430
> foo(1)[0] -- argv[0]
lua5.3


Lua 5.1.5  Copyright (C) 1994-2012 Lua.org, PUC-Rio
> function foo(...)
>> return arg
>> end
> =foo(1,2,3)[0] -- lua table (i.e. not argv), 1-indexed
nil
> =foo(1,2,3)
table: 0x56228a2c3d20
```

I think we should make sure that 5.3 doesn't introduce unexpected breakage anywhere else.

**Comment by wilhelmy** [comment]
In both 5.3 as well as 5.1 you can access the arguments via "...", but I'm not sure that still works in 5.0 (maybe we can deprecate 5.0, it's from 2003-2006)

**Comment by wilhelmy** [comment]
https://www.lua.org/manual/5.0/manual.html#2.5.8 Ctrl+F variadic

Compare that to 

https://www.lua.org/manual/5.1/manual.html#2.5.8 Ctrl+F variadic

Seems to me they replaced the implicit "arg" parameter by the new "..." form of accessing the arguments, but kept arg for compatibility reasons.

**Comment by wilhelmy** [comment]
```
Lua 5.0  Copyright (C) 1994-2003 Tecgraf, PUC-Rio
> function foo(...)
>> return ...
stdin:2: unexpected symbol near `...'
```
yup, seems that way.

**Comment by knixeur** [comment]
https://www.lua.org/manual/5.1/manual.html#7.1

Migrations have been done to comply with new format for example b2b17559df04ce47352852545cdd44e18f812aae but this is >=5.1, I think dropping support for 5.0 will make our lives easier.

**Comment by raboof** [comment]
I agree we should drop support for Lua 5.0 and start requiring Lua 5.1. Even though Debian still ships `lua50` it also has newer versions.

**Comment by wilhelmy** [comment]
I'm also in favour of dropping 5.0 because there is no workaround for this other than preprocessing the lua code (yikes), because using ... in 5.0 results in a syntax error.

I've just checked, Lua has preview releases for 5.4, and there seems to be nothing incompatible this time: https://www.lua.org/work/doc/manual.html#8
