### ISSUE TITLE
Consider replacing `run-mailcap` by `xdg-open` in the default config

### ISSUE THREAD

**Issue by wilhelmy** [raboof/notion#144]
Should be more portable and use the system's standard MIME database instead of yet another one (I assume run-mailcap uses `~/.mailcap`)

**Comment by knixeur** [comment]
I agree, xdg-open has been around for a long time and works fine.

**Comment by wilhelmy** [comment]
The only question left to answer is whether it has an equivalent of `run-mailcap --action=edit`.

**Comment by knixeur** [comment]
Mmm you're right, I seldome use this options, maybe Edit can be dropped since editable stuff is usually opened with it's editor (IE: png->gimp, c->vim) the most common problematic cases I can think of are html files.

**Comment by raboof** [comment]
I see a bare Arch install doesn't install run-mailcap but does seem to have xdg-open.

Should we switch to xdg-open or have both options side by side?

**Comment by wilhelmy** [comment]
Maybe xdg-open for open, run-mailcap for edit?
