### ISSUE TITLE
Update documentation

### ISSUE THREAD

**Issue by wilhelmy** [raboof/notion#145]
Currently, the documentation still mentions `submap_wait`.
We should make sure all other functions which were removed are removed from the documentation and documentation is generally up-to-date whereever things have changed.

**Comment by raboof** [comment]
Good one! I think it also has `kpress_wait`, which I think is also gone

**Comment by wilhelmy** [comment]
How's the documentation currently generated, btw?

**Comment by raboof** [comment]
using the Makefile in the notion-doc project. It's not currently automatically rebuilt and updated, though, IIRC

**Comment by raboof** [comment]
(doc sources are updated, leaving this ticket open until we have actually deployed them though)

**Comment by raboof** [comment]
now they're regenerated and uploaded to https://raboof.github.io/notion-doc/notionconf/node4.html#sec:binddef on each merge to notion-doc master
