### ISSUE TITLE
Honour mod_dock min_w/min_h

### ISSUE THREAD

**Issue by raboof** [raboof/notion#149]

**Comment by raboof** [comment]
Might be an unintended sideeffect of #95, though I'm surprised they go through the winprops mechanism then.

**Comment by wilhelmy** [comment]
Hm.. seems it still works and I just removed the winprop for dock, either intentionally or by copying over the old config file. It looks stupid though, at least with h=64: https://barfooze.de/i/fukushima-2019-07-09_16:27:25.png

**Comment by raboof** [comment]
Thanks for checking!
