### ISSUE TITLE
Create an example look.lua that works well on hidpi screens

### ISSUE THREAD

**Issue by raboof** [raboof/notion#180]
Perhaps even make it the default?

Something like https://pastebin.com/u83cBEDA

**Comment by rabarbar42** [comment]
Could the xft font size be made smaller? 16 is a bit overkill.

**Comment by raboof** [comment]
Any smaller is not really readable on my 15" 3200x1800 screen - what kind of screen are you testing with?

**Comment by rabarbar42** [comment]
I tested on a 'regular' FHD screen (1920x1200), so not really hidpi. Could the font be scaled by, say defining it as a percentage of vertical screen size probed from xrandr?

**Comment by raboof** [comment]
Added with a check so it's only loaded by default when the screen width > 3200px

**Comment by wilhelmy** [comment]
Question, how should a mixed-dpi setup be handled?

**Comment by raboof** [comment]
We don't currently have a nice way for this, though it would be an interesting exercise. In practice I just pick a font size which is slightly too small for the hidpi screen and slightly too large for the regular screen :D
