### ISSUE TITLE
interesting..

### ISSUE THREAD

**Issue by dobkeratops** [raboof/notion#2]
It's great that this is useable with a mouse, I've seen the ability to drag windows between frames;

has anyone tried to extend the mouse support to allow creating splits - e.g. by dropping a window in the left/top/upper/lower region of a frame, create a new split there, or drop nearer the centre(or directly on the titlebar) to add to the existing frame; show the action with a rectangular highlight + icon. Similar to the behaviour of the internal tilling managers in IDEs like visual studio or eclipse.

Whenever I've tried a tiler I always go back to floating because its' hard to remember the keybindings... but I use emacs with a tiled layout and 'wind move' hotkeys. Perhaps some popup menu when you hold 'super' could assist

**Comment by raboof** [comment]
I'm not aware of anyone working on such support. If you'd want to discuss this further, you might want to try the mailinglists at http://sourceforge.net/p/notion/mailman/?source=navbar or add some more focused feature requests in the tracker here. Thanks!
