### ISSUE TITLE
Background is gray rather than black

### ISSUE THREAD

**Issue by raboof** [raboof/notion#204]
Reported by @dkogan on the mailinglist:

> In my look the empty-pane color used to be black, but now it's gray. Empty panes come up when I create a new workspace with ioncore.create_ws(_). This is also the filler color used to cover empty space if a window doesn't completely fill a tab. Do you know what style thing controls this?

I wonder if we write to this space at all? Reportedly no external compositors or background apps in use.

[look_dima.lua.txt](https://github.com/raboof/notion/files/3697124/look_dima.lua.txt)

**Comment by wilhelmy** [comment]
If you set an X11 background image, it won't be visible in Notion — this sounds like the same mechanism to me... IIRC it's possible to change it to transparent somehow?

**Comment by knixeur** [comment]
I found something related to this a few months ago, here's a commit I made with some tests: https://github.com/knixeur/notion/commit/ec935ddc2a2d6d1ed1d30dad8ae5f2a80d0e28a0

**Comment by raboof** [comment]
Unless I'm misunderstanding, the color of 'empty space' is determined by the `background_color` of `*`, which in the attached `look_dima.lua` is indeed grey (`#d8d8d8`).

This might be a change from the notion3 behavior, but it seems correct to me?

Closing this ticket for now - the notes by @knixeur about glitches from prior workspaces on empty workspaces sound like a different issue, that deserves its own ticket?

**Comment by dkogan** [comment]
I don't know what's "right", but making that change makes other things
worse. Specifically, pop-up text boxes (like the "run..." box popped up
by mod_query.query_exec()) come up all black: both the text and the
background

**Comment by raboof** [comment]
> but making that change makes other things
worse. Specifically, pop-up text boxes (like the "run..." box popped up
by mod_query.query_exec()) come up all black: both the text and the
background

Well, yes: if you change the default background color to 'black' but keep the default foreground color on 'black' also you'll.. get what you asked for :).

The style of 'query' boxes (like the "run..." box popped up by mod_query.query_exec()) is determined by the 'input' style, so if you want to tweak those colors you can do that there.

**Comment by dkogan** [comment]
Arnout Engelen <notifications@github.com> writes:

> Well, yes: if you change the default background color to 'black' but
> keep the default foreground color on 'black' also you'll.. get what
> you asked for :).

But it used to work for years and years! :)

I need to go back and see if there are other issues that prevent me from
switching to the new builds full time. I see problems periodically, but
they may not be related to the update.

Do you have a list of things to finish before you want to release the
new build?

**Comment by raboof** [comment]
> But it used to work for years and years! :)

Perhaps we just fixed a long-standing bug? :smile: . I'll have another look to see if I can explain the where the old behavior came from.

> Do you have a list of things to finish before you want to release the new build?

Yes: https://github.com/raboof/notion/projects/1. Almost there it seems :crossed_fingers: !

**Comment by raboof** [comment]
> I'll have another look to see if I can explain the where the old behavior came from.

You include `lookcommon_emboss.lua` in your style. Notion 4 ships the version of lookcommon_emboss.lua from a6f9c6b3032b49a88332cabf7a4796a51f6972d7. Unfortunately, various 'tweaks' were made to those includes in the period where Ion was licensed under the Ion license. For that reason we cannot include those changes in the LGPL Notion 4.

I don't think we have a choice but to accept that custom styles relying on the changes made in the period where Ion was developed under the Ion license will need some updates to work with Notion 4. That's unfortunate, but I don't see an alternative, and this is the sort of change that can be in a major version update...

**Comment by raboof** [comment]
(added a note in #282)
