### ISSUE TITLE
Margin on top of the screen

### ISSUE THREAD

**Issue by raboof** [raboof/notion#205]
Reported by @dkogan on the mailinglist:

> I think the margin between the top of the tab bar and the top of the screen has increased by a few pixels. Do you know what controls this?

[look_dima.lua.txt](https://github.com/raboof/notion/files/3697124/look_dima.lua.txt)

**Comment by wilhelmy** [comment]
Might be mod_dock with a minimum size?

**Comment by knixeur** [comment]
I think this was related to #206 ?

**Comment by raboof** [comment]
I don't think that was confirmed, will email ;)

**Comment by raboof** [comment]
confirmed fixed!
