### ISSUE TITLE
No mod_dock minimum height

### ISSUE THREAD

**Issue by raboof** [raboof/notion#206]
We're enabling mod_dock by default for Notion 4.

By default, mod_dock takes up space even when there is nothing inside it. It would be nice if we could avoid that.

**Comment by wilhelmy** [comment]
Does it though? I thought that was a configuration mistake on my part?

**Comment by knixeur** [comment]
iirc it does when there was something temporarily on it. I'm using polybar right now, and if I kill it dock still takes the space used for it.

**Comment by raboof** [comment]
> Does it though? I thought that was a configuration mistake on my part?

Actually you're mentioning exactly this issue in that thread, https://github.com/raboof/notion/issues/149#issuecomment-509665724 ;)

**Comment by raboof** [comment]
(the defaults put it at the bottom-left rather than the top-left, which is a bit less bad, but still :)

**Comment by raboof** [comment]
> https://github.com/raboof/notion/blob/master/mod_dock/dock.c#L782
> When you kill something, n_dockapps is now 0 and defaults to tile_size. I guess if n_dockapps is 0, width and height should be 0?

Makes sense to me, though it seems this was intentionally changed in 6098344ec70400160f9dbfe7019c072bb34b3595 it doesn't clarify why ;)
