### ISSUE TITLE
ion-statusd going to 100% cpu

### ISSUE THREAD

**Issue by raboof** [raboof/notion#213]
Since upgrading to latest git, I've noticed ion-statusd going to 100% cpu. strace shows it receiving SIGALRM over and over again

reported by @trazillion on IRC

**Comment by raboof** [comment]
I think @knixeur has done some digging in this area, but AFAIK hasn't been able to reliably reproduce it.

Of course it would still be great to fix it, but perhaps we should move it out of the critical path for notion4

**Comment by dnr** [comment]
I just recently upgraded from 3 to 4 and this has been happening to me multiple times a day. I haven't tried debugging deeply yet (beyond a quick strace).

**Comment by dnr** [comment]
The problem appears to be here: https://github.com/raboof/notion/blob/master/libmainloop/signal.c#L86-L87
If the timer is set to go off in 1µs, the interval will be set to 1µs, and the kernel will attempt to deliver 1 million signals per second to the process. It happens on my laptop that this is enough that the main loop never gets a chance to run and reset the timer. (The signal handler itself only sets a global flag.)

There's no reason why this should be an interval timer at all, it only needs to be one-shot to get woken up for the next queue event. I tried removing the `it_interval` lines entirely, but ion-statusd got stuck and stopped updating. I made the interval a fixed 100ms just to handle the case where the signal gets "lost" (i.e. it's delivered but then some other code runs that unsets the flag before the main loop notices), and that seems to be working fine for now.

According to git history, those lines date back to 2005 or earlier, and I can't find an explanation for them. Overall this code seems... not very good. If you look with strace, you can see it actually calls setitimer twice per iteration (I haven't figured out exactly why). And overall, letting each statusd module set its own timer causes a lot more wakeups than needed if they were synchronized on one or a few timers. Not a big deal, but it suggests that this could be simplified quite a bit, e.g., forget SIGALRM, just sleep 1s per iteration and check timers then (for ion-statusd only, not other users of libmainloop).

Does anyone have thoughts on which direction the project might want to go in for a permanent fix?

**Comment by raboof** [comment]
> There's no reason why this should be an interval timer at all

That indeed looks really suspect.

> it's delivered but then some other code runs that unsets the flag before the main loop notices

Yeah, there seem to be a lot of opportunities for race conditions here (shouldn't we also take into account the cache flushing on multiple cores?)

> this could be simplified quite a bit, e.g., forget SIGALRM, just sleep 1s per iteration and check timers then (for ion-statusd only, not other users of libmainloop).
> Does anyone have thoughts on which direction the project might want to go in for a permanent fix?

I think I would prefer fixing the signals infrastructure for all use cases over doing something specific for ion-statusd - but I would be happy with either solution, so it's up to whoever takes this task on ;).

**Comment by wilhelmy** [comment]
Quoting setitimer(2):
> **CONFORMING TO**
>       POSIX.1-2001, SVr4, 4.4BSD (this call first appeared in 4.2BSD).  POSIX.1-2008 marks getitimer() and
>       setitimer()  obsolete,  recommending  the  use of the POSIX timers API (timer_gettime(2), timer_set-
>       time(2), etc.) instead.

Although if it weren't broken, I wouldn't necessarily suggest fixing it. Just my 2c.

**Comment by dnr** [comment]
I've been running with a simple patch to use a 100ms interval for over a month now and haven't had any issues. There are certainly better ways to improve this code, but it's such a low priority I'll probably never get around to it. I'll send a PR for my simple patch.
