### ISSUE TITLE
mod_statusbar not launching anymore

### ISSUE THREAD

**Issue by sebhz** [raboof/notion#233]
I gave a try to Ion4 recently - and mod_statusbar does not seem to launch anymore. I'm using notion4, compiled from source (6808963a306079460 commit-id), on CentOS7 - everything else seems to be working as expected.

I am well aware that mod_dock is now the default, and that dock and statusbar are mutually exclusive, but I like the good old statusbar.

So I just tried to replace `dopath("mod_dock")` by `dopath("mod_statusbar")` in cfg_defaults.lua... When launching notion, I get a `mod_statusbar.lua:338: Failed to create statusbar.` message.

Did I miss something with the configuration ? Or was this a known issue leading to defaulting to mod_statusbar ?

Note that mod_dock is working fine - with the default config I get a dock !

BTW, the comments in cfg_notion.lua, are wrong, with respect to mod_dock and mod_statusbar, and the migration guide could explicitly mention that dock is now the default - I'll gladly submit a small patch to fix these small issues ).

**Comment by raboof** [comment]
> I gave a try to Ion4 recently (..) everything else seems to be working as expected.

Thanks for trying it, that is valuable feedback!

> When launching notion, I get a mod_statusbar.lua:338: Failed to create statusbar. message.
I can reproduce that - let me look into it.

> BTW, the comments in cfg_notion.lua, are wrong, with respect to mod_dock and mod_statusbar, and the migration guide could explicitly mention that dock is now the default - I'll gladly submit a small patch to fix these small issues ).

That would be great!

**Comment by sebhz** [comment]
I did a quick bisect, and found that the problem lies with commit 5ecf25829d90ed172 - to be precise, the part of this commit that moves the ` gr_read_config()`  line. I did not investigate further, but moving this line back to its original position gives me back the statusbar (though notion complains about mod_sm not being found anymore...).
Hope this helps...

**Comment by raboof** [comment]
That's a very useful data point. I moved the `gr_read_config` line in that commit to make sure the screen dimensions are available when the look is loaded. That still seems useful. Let's see if we can get both somehow.

**Comment by raboof** [comment]
I have a potential fix  - https://github.com/raboof/notion/pull/239 - though I'm not sure if this would introduce other problems. Would appreciate it if you could give it a try!

**Comment by sebhz** [comment]
It seems to work fine - at least I get my statusbar with this patch. Drawing engine is properly loaded. Theme switching works well. No error reported. This hardly qualifies as full exhaustive testing, but it is goog enough for me.

I had to comment out a malformed TR line to get notion to compile though - line 104 in saveload.c. I did not check the CI log, but I guess it was also caught there.

**Comment by raboof** [comment]
> This hardly qualifies as full exhaustive testing, but it is good enough for me.

Cool, I'll merge to master soon to get some wider testing

> I did not check the CI log, but I guess it was also caught there.

Oops, indeed
