### ISSUE TITLE
Fonts in xephyr

### ISSUE THREAD

**Issue by raboof** [raboof/notion#240]
The default font is currently `-*-helvetica-medium-r-normal-*-12-*-*-*-*-*-*-*`.

That seems like a fine default, but when running with inside xephyr for testing it seems only `-*-fixed-*-*-*-*-*-*-*` fonts seem to be available (and xft fonts). Is that normal? Or perhaps something strange in my linux distribution (NixOS)

/cc @dradetsky

**Comment by wilhelmy** [comment]
Seems to work for me
![fukushima-2020-01-19_23:48:48](https://user-images.githubusercontent.com/4211529/72689855-4b7ca280-3b16-11ea-855d-7eff1ad5edc0.png)

**Comment by raboof** [comment]
Ah, seems like a nixos-specific problem then. Thanks!

**Comment by raboof** [comment]
Ah, more information at #28599
