### ISSUE TITLE
SDL2 based applications cannot enter full screen

### ISSUE THREAD

**Issue by grapeli** [raboof/notion#244]
In the case of a dosbox, it looks like this.
https://drive.google.com/open?id=1xXkl0EXJbghDgNhVl__95LPfpqAUFV8F
Pre-build [dosbox-staging](https://www.vogons.org/download/file.php?id=74181).

The same happens for the test application testdraw2 which is the source part of SDL2.

Both work without problems under i3. I don't know where the problem is. In sdl2, xorg or maybe notion? How to diagnose and fix it.
Everything takes place under archlinux.

Is this problem similar to Adobe Flash fullscreen?
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=462690
or
https://bugzilla.libsdl.org/show_bug.cgi?id=1859

**Comment by grapeli** [comment]
After applying this [patch](https://bugzilla-attachments.libsdl.org/attachment.cgi?id=2810) to SDL2, finally the applications correctly enter fullscreen.
The problem can be solved.

**Comment by raboof** [comment]
Cool! What upstream issue was this patch attached to?

**Comment by grapeli** [comment]
> Cool! What upstream issue was this patch attached to?

No. I am not a developer to pull this topic and justify it properly.
However, it is worth looking at even more closely. If you feel up to it, do it.
I test so.
```
curl -JOL https://www.libsdl.org/release/SDL2-2.0.10.tar.gz
tar xf SDL2-2.0.10.tar.gz
cd SDL2-2.0.10
./configure --prefix=/usr --disable-shared
make -j4
cd test/
gcc -o testdraw2 testdraw2.c -g -O2 -I../include -D_REENTRANT -DHAVE_OPENGLES2 -DHAVE_OPENGL -L../build/.libs -lSDL2_test -lSDL2 -pthread -lm -ldl -lrt -lunwind-x86_64 -lunwind
./testdraw2 --help
./testdraw2 --info all   #fullscreen alt-enter
```
I noticed that the fullscreen with software renderer works fine even after undoing this [commit](https://hg.libsdl.org/SDL/raw-rev/f931db466859).
`SDL_RENDER_DRIVER=software ./testdraw2 --info all`

**Comment by grapeli** [comment]
A broken fullscreen in SDL2 was finally [fixed](https://hg.libsdl.org/SDL/rev/204628027601) five days ago. Finally!
