### ISSUE TITLE
Error on start up - Creation of "WClientWin" returned null / Creation of "WGroupCW" returned null

### ISSUE THREAD

**Issue by hilprl** [raboof/notion#252]
Hi all, 

I am looking for some help. Recently installed Notion on my laptop running Debian Buster and seeing this error during the start up.  

Notion version - 3-2019050101-646-g1689260
Debian GNU/Linux 10 (buster)

```
Notion startup error log:
>> Creation of "WClientWin" returned null
>> Creation of "WGroupCW" returned null
```

I am wondering what is causing the above errors. Notion was installed using the instructions here.

Thanks in advance.

**Comment by raboof** [comment]
Thank you for raising this issue!

These log messages were added relatively recently while fixing #239 . I assumed there that this would be an error condition that should not happen, and thus deserved a more prominent error message. As you're not seeing other problems, apparently there are also healthy cases where this condition occurs. I'll remove the warning.

**Comment by hilprl** [comment]
> Thank you for raising this issue!
> 
> These log messages were added relatively recently while fixing #239 . I assumed there that this would be an error condition that should not happen, and thus deserved a more prominent error message. As you're not seeing other problems, apparently there are also healthy cases where this condition occurs. I'll remove the warning.

Thanks for your reply and many thanks for this wonderful project.  I am really enjoying Notion and still going through the man page and config files to try out different features.

**Comment by raboof** [comment]
Thanks! Let us know if you have any further feedback ;)
