### ISSUE TITLE
Notion + Gnome3

### ISSUE THREAD

**Issue by buhl** [raboof/notion#272]
I am getting old...
So, I changed my laptop OS from gentoo to ubuntu (20.04). I was getting tired of compiling things on my slow laptop, configuring kernel to get all the hardware support and generally having to tinker to get things working. (I still run gentoo on my desktop PC)

So after learning to live with older packages of EVERYTHING I started to think what else than stability could I put on my pro/con list as a pro. I thought that maybe I could make use of all the gnome things the ubuntu guys are doing so found a repository that did the same for i3 and adapted it to notion.

https://github.com/buhl/gnome-flashback-notion

I am not sure if this place is the right place to post about this, but I thought i might helpful for someone.

**Comment by raboof** [comment]
Interesting! It might be good to update the 'What do I'll get by installing it?' section to explain that it's perfectly possible to use gnome utilities with 'plain notion', and show in more detail what additional features you get by wrapping it in a gnome session.

Feel free to send a PR linking to that repo from https://notionwm.net/software.html!

**Comment by buhl** [comment]
I'll try to throw something together. What repo holds the website?

**Comment by raboof** [comment]
The website is in the `gh-pages` branch of this repo

**Comment by buhl** [comment]
Ah, thanks. I am learning a lot about github these days :)
I am having some issues with notions under gnome at the moment. but I am also running ubuntu 20.04 development branch so I am not sure what is causing what at the moment. When 20.04 stabilizes (some time this month) I will revisit and reexamine. Can I keep this issue open until then?

**Comment by raboof** [comment]
Sure, no problem!

**Comment by buhl** [comment]
After evaluating this for some months I have come to the conclusion that it gives more
hassle than good running notion under Gnome3.
I have now decided to move away from this and run plain notion like in the good old days
:)
So I am closing this issue now, but might revisit the idea later on.
