### ISSUE TITLE
Audacity tooltip issue

### ISSUE THREAD

**Issue by kristopolous** [raboof/notion#285]
I'm using 4.0.0-7-g6c76b177 and at least in audacity 2.3.3 this is what my tooltips are looking like
![audacity](https://user-images.githubusercontent.com/231761/83310375-ad35d300-a1c0-11ea-83fc-bae147b33b39.png)

**Comment by raboof** [comment]
Looking with `xwininfo -root -tree`, I indeed see a 400x250 window:
```
        0xe0001d "Tiling Frame<3>": ()  1359x493+0+0  +0+0
           13 children:
           0xe0d11e "Framed PHolder Frame": ()  404x254+477+238  +477+238
              1 child:
              0x9a0128d (has no name): ("audacity" "Audacity")  400x250+2+2  +479+240
                 1 child:
                 0x9a0128e (has no name): ()  1x1+-1+-1  +478+239
```

Looking with xtrace audacity indeed seems to ask for a window with those dimensions:

```
000:<:22400: 28: Request(62): CopyArea src-drawable=0x07801134 dst-drawable=0x07801144 gc=0x07800392 src-x=0 src-y=0 dst-x=0 dst-y=0 width=130 height=25
000:<:225d3: 52: Request(1): CreateWindow depth=0x18 window=0x07801146 parent=0x000001a1 x=0 y=0 width=400 height=250 border-width=0 class=InputOutput(0x0001) visual=0x00000020 value-list={background-pixel=0x00000000 border-pixel=0x00000000 bit-gravity=NorthWest(0x01) event-mask=KeyPress,KeyRelease,ButtonPress,ButtonRelease,EnterWindow,LeaveWindow,PointerMotion,Exposure,VisibilityChange,StructureNotify,FocusChange,PropertyChange colormap=0x00000022}
000:<:225ea: 20: Request(70): PolyFillRectangle drawable=0x07801146 gc=0x0780000a rectangles={x=0 y=0 w=400 h=250};
```

**Comment by kristopolous** [comment]
alright, that's there problem I guess?

**Comment by raboof** [comment]
> alright, that's their problem I guess?

It's hard to say, it could be something on our side that makes them pick 400x250, or an option to make the window 'transparent' that we don't support.

For now I'm assuming it's something on their side, though. Let's continue here when we find an indication that suggests otherwise.

**Comment by dkogan** [comment]
Are you still seeing this? It works for me today with the latest notion and audacity from Debian.

**Comment by raboof** [comment]
I'm not seeing this anymore on audacity 2.4.2 (from nixos-unstable 7cbec40a09533dd9c525d6ab94dddfe77768101a).

This might also have to do with gtk/qt versions, of course. NixOS is using gtk2 and qt4 for audacity:

```
$ ldd `which audacity` | grep libgtk
	libgtk-x11-2.0.so.0 => /nix/store/9fyhdgrnzksir17bhksvjbqzw80f98h9-gtk+-2.24.32/lib/libgtk-x11-2.0.so.0 (0x00007fab2e8bc000)
$ ldd `which audacity` | grep -i qt
	libsuil-0.so.0 => /nix/store/6s6k97lr56xmk48xs1avdmilxcx5wyai-suil-qt4-0.10.6/lib/libsuil-0.so.0 (0x00007fe3b0d39000)
```

**Comment by kristopolous** [comment]
confirmed. issue no longer replicable.

**Comment by raboof** [comment]
Great! Thanks for the follow-up!
