### ISSUE TITLE
untiling crash

### ISSUE THREAD

**Issue by kristopolous** [raboof/notion#290]
This is related to #288 .. I'm getting a null pointer under the same condition (vnc window) when right clicking and going to untile. There's some wacky window geometry ... I haven't gotten to the bottom of it but I can readily reproduce it

**Comment by raboof** [comment]
Can you get a coredump/backtrace?

**Comment by kristopolous** [comment]
Yep. This ticket is mostly for notes . I'll get a fix out eventually

**Comment by kristopolous** [comment]
I had a libray mismatch. user error.

**Comment by raboof** [comment]
Good to know, thanks for opening an issue regardless!
