### ISSUE TITLE
Chrome windows don't refresh when tabbed into focus

### ISSUE THREAD

**Issue by drheld** [raboof/notion#314]
With notion 4.0.1, switching tabs from one Chrome window to another doesn't redraw the screen. I'm not sure exactly what it is, but it's deterministic. One such affected site is https://drheld.github.io/nyc_covid19/?zip=11217 .

Downgrading to notion 3.2 fixes the issue. With 4.0.1 it reliably reproduces.

**Comment by raboof** [comment]
> switching tabs from one Chrome window to another

I'm not sure I understand the scenario you're describing?

**Comment by drheld** [comment]
Sorry for being unclear. I should have documented it while it was reproducing. Here's a simple setup.

1) Create a desktop with 1 frame with 2 notion tabs. Have a Chrome tab in each.
2) In one notion tab have a Chrome window at at something like google.com, in the other notion tab have a Chrome window at https://drheld.github.io/nyc_covid19/?zip=11217
  i) Note: Some sites consistently demonstrate the problem, while others consistently don't. Google does not. More graphical ones seem to including above mentioned link.
3) Switch notion tabs from the graphical one to the non-graphical one and back.
4) The notion tab content remains the same (ie: google.com) instead of redrawing the graphs.

Is that more clear?

**Comment by buhl** [comment]
Is this only related to chrome? I tried chromium on ubuntu and I have no issues.
What notion style are you using?

**Comment by drheld** [comment]
I've only seen the issue in Chrome. I'm not sure what you mean by style exactly, but this is old lua files upgraded from ion.

**Comment by buhl** [comment]
@drheld Could you try to start notion with the standard config?

I have seen issues like you describe when having transparent background enabled.

**Comment by drheld** [comment]
After doing experiments and rolling back to Notion 3.2, it turns out it does not fix the issue afterall. Given that, it sounds like the actual issue is likely an interaction of a new Chrome version and Notion (both old and new versions).

**Comment by wilhelmy** [comment]
You could start from the last known good packaged chromium release and sort of bisect from there by installing different chrome releases... sounds a little tedious. Then we could compare diff the first broken release against the last known good and perhaps see which Xlib functions it calls differently (might be more involved, browsers are complicated after all). Doesn't seem like any of us others can reproduce this.

**Comment by buhl** [comment]
What version of Chrome do you see the problem with? And have you tried starting notion with the default config?

**Comment by drheld** [comment]
Got confirmation that this is indeed a Chrome bug. Sorry about the bother (filed here when it looked downgrading Notion had fixed it).

**Comment by drheld** [comment]
https://chromium-review.googlesource.com/c/chromium/src/+/2724872

**Comment by raboof** [comment]
> Sorry about the bother

No problem at all! I think it's totally fine to open tickets here when it's not clear yet where the problem is exactly. Hopefully this gets resolved soon!
