### ISSUE TITLE
mod_sp: set default width/height of the scratchpad from cfg_sp.lua

### ISSUE THREAD

**Issue by wilhelmy** [raboof/notion#320]
Currently it's a compile-time constant that's set to 640/480 which is very small on modern setups.

My idea would be to add a `mod_sp.set{ default_width=800, default_height=600 }` function (and a corresponding `get` function) similar to `ioncore.{get,set}`, unless someone has a better idea what an API that sets module specific values should look like because module specific settings that are not attached to one of the object hierarchy objects are kind a bit of an outlier that currently does not exist in notion aside from core.

**Comment by buhl** [comment]
I had a little fun with scratchpads lately. I basically reimplemented mod_sp in lua with some ekstra things on top  in #317.
I think we could move mod_sp to be intirerly implimented in lua without users being effected.

Actually I have been spending some time in the notion codebase generally and I think this could be done more places if we wanted to.

**Comment by wilhelmy** [comment]
mod_sp as it is doesn't seem to do much, and seems buggy. I'm all in favour of replacing C by a more modern language where possible. Will look at the code some time.
