### ISSUE TITLE
[notionwm.net] Links to Arch and Nix packages broken

### ISSUE THREAD

**Issue by vallode** [raboof/notion#363]
The links leading to the package on the homepage (https://notionwm.net/) for both Arch and NixOs are broken. Arch leads to a 404 (Repo should be `extra`) and NixOs has the wrong query parameters (should be `?channel=unstable&query=notion`). Not a biggie but though I'd chuck this in.

**Comment by wilhelmy** [comment]
Thanks, next time feel free to make a pull request against the gh-pages branch ;)
