### ISSUE TITLE
Java (swing/awt) problems

### ISSUE THREAD

**Issue by olejorgenb** [raboof/notion#37]
Example application that misbehaves: https://github.com/VUE/VUE/releases/download/3.3.0/VUE.jar

`java -jar VUE.jar` and place the main window in a rightmost split. Right click or use the menu. The result is not good:
![2017-01-17-135036_1366x768_scrot](https://cloud.githubusercontent.com/assets/72201/22021192/213f6fb8-dcbc-11e6-96a3-6d3bb82c7c4f.png)

AWT use a dedicated x-window for its menus. It is positioned relative to the root window even though notion reparent it under the `WGroupCW` window.

I've tried various combinations of `wmname` and `_JAVA_AWT_WM_NONREPARENTING` to no avail :(

The closest I've come to a fix is to use a `clientwin_do_manage_alt` hook taking complete control over the placement of these windows, (`Instance: sun-awt-X11-XWindowPeer`) manually converting the absolute coordinates to relative. This works for the context menu, but not the menubar menu.

I assume this is a problem for other notion users too, but eg. https://github.com/raboof/notion/blob/master/etc/cfg_kludges.lua#L65 indicates that some awt java apps at least partially works? If someone can confirm/deny the problem I'd be thankful.

Possibly related commit: https://github.com/raboof/notion/commit/0cd1e04960312d5c1c1a28efe5bc9f3453e33de2

**Comment by raboof** [comment]
So making them transient (like I did for IntelliJ) did not help?

IntelliJ basically should work fine with these kludges in place.

**Comment by olejorgenb** [comment]
Nope, I'll install intelliJ and test a bit.

This works though: (the menu get's a titlebar though :P)
    
    defwinprop {
      instance = "sun-awt-X11-XWindowPeer",
      userpos = true,
      target="WScreen",
      float = true,
    }

**Comment by olejorgenb** [comment]
Now I start to think this an application specific issue. Although I'm sure I've had a similar problem with other java apps, I'm unable to reproduce it for the one's I remember (eg. protege).

IntelliJ's menu window is marked as `overrideRedirect" while the vue menu window is not. The vue window has a curious name though: "###overrideRedirect###" Digging around it seems this might've been a (old?) way to get swing/awt to mark the window as overrideRedirect.

I'll close this issue and reopen it if I come across other applications in the future.
