### ISSUE TITLE
Ghidra drag and drop does not work

### ISSUE THREAD

**Issue by edmcman** [raboof/notion#370]
Dragging and dropping panes in Ghidra, which uses Java swing, does not work properly.

Expected behavior:

![Recording 2024-07-22 at 16 12 17](https://github.com/user-attachments/assets/8b68aef8-2302-4e62-a5ed-8720742ca926)

Notion's behavior:

![Recording 2024-07-22 at 16 17 55](https://github.com/user-attachments/assets/01dd62de-bda1-4bc0-8e60-5dc19eb50322)

Notion actually moves the pane into a new window (which is not seen because I am recording the original window).

Maybe related to #242?

**Comment by edmcman** [comment]
Oddly enough, I've been playing with this, and I've had some bizarre behavior.  In most cases, I get the cursor showing drag and drop is not possible.  In some cases, drag and drop worked.  In another case, drag and drop worked, but went to the terminal behind the active window!

**Comment by edmcman** [comment]
![Recording 2024-07-23 at 12 50 02](https://github.com/user-attachments/assets/8d00f7ba-5265-4d58-9d57-0324b961bf75)

**Comment by knixeur** [comment]
Mmm I remember having troubles with Java apps before, have you tried `_JAVA_AWT_WM_NONREPARENTING=1`? I don't remember if I used this to fix them on notion or volare (currently on volare)
```bash
netbeans.sh
2:_JAVA_AWT_WM_NONREPARENTING=1 $HOME/.local/opt/netbeans/bin/netbeans

soapui.sh
2:_JAVA_AWT_WM_NONREPARENTING=1 $HOME/.local/opt/SoapUI-5.7.0/bin/SoapUI-5.7.0
```

**Comment by edmcman** [comment]
Thanks @knixeur -- that did not fix this particular problem :-(

**Comment by edmcman** [comment]
Here is an `xtrace` log of the Java program: [xtrace.log](https://github.com/user-attachments/files/16364477/xtrace.log)

At t=7.620, I held down the left mouse button to drag.  For a few seconds, I did not move the mouse.  Then I moved the mouse, and continued to hold the mouse button for a few seconds, until t=17.352.

These are the relevant windows to the problem:
```
        0x3600076 "WFrame<5>": ()  1720x1414+0+0  +1440+2000
           4 children:
           0x36484f2 "Notion GroupCW": ()  1x1+2+30  +1442+2030
           0x9400305 "less /tmp/xwininfo.log  /home/ed": ("gnome-terminal-server" "Gnome-terminal")  1714x1364+3+39  +1443+2039
              1 child:
              0x9400306 (has no name): ()  1x1+-1+-1  +1442+2038
           0x7200007 "Drag and Drop Example": ("com-sun-tools-javac-launcher-Main" "com-sun-tools-javac-launcher-Main")  1716x1382+2+30  +1442+2030
              2 children:
              0x720001f "FocusProxy": ("Focus-Proxy-Window" "FocusProxy")  1x1+-1+-1  +1441+2029
              0x720001c "Content window": ("com-sun-tools-javac-launcher-Main" "com-sun-tools-javac-launcher-Main")  1716x1382+0+0  +1442+2030
           0x3625594 "Notion GroupCW": ()  1x1+-1+-1  +1439+1999
```

In particular, 0x7200007 is the Java program, and 0x9400305 is the terminal behind it that ultimately receives the dragged text.

Here are the first few mentions of 0x9400305 in the log:
```
11.984 000:>:042e:48: Reply to QueryTree: root=0x000009a0 parent=0x03600017 children=0x03625594,0x07200007,0x09400305,0x036484f2;
11.984 000:<:042f: 24: Request(20): GetProperty delete=false(0x00) window=0x09400305 property=0x18a("WM_STATE") type=0x18a("WM_STATE") long-offset=0x00000000 long-length=0x00000001
11.984 000:<:0430: 24: Request(20): GetProperty delete=false(0x00) window=0x09400305 property=0x1b3("XdndAware") type=any(0x0) long-offset=0x00000000 long-length=0x00000001
11.984 000:<:0431: 24: Request(20): GetProperty delete=false(0x00) window=0x09400305 property=0x1b4("XdndProxy") type=0x21("WINDOW") long-offset=0x00000000 long-length=0x00000001
11.984 000:<:0432: 44: Request(25): SendEvent propagate=false(0x00) destination=0x09400305 event-mask=0 ClientMessage(33) format=0x20 window=0x09400305 type=0x1bc("XdndEnter") data=0x08,0x00,0x20,0x07,0x01,0x00,0x00,0x05,0x83,0x01,0x00,0x00,0x1b,0x02,0x00,0x00,0x1f,0x00,0x00,0x00;
```

Ar around line 1767 or t=11982, it seems like the application is trying to figure out which window has the focus.  It queries for children of 0x9a0, the root window, and then issues a bunch of queries for `WM_STATE`.  On 0x9400305, it receives a non-zero response of 3, and then queries for `XdndAware`.  It then appears to stop its search and conclude that 0x9400305 has focus.

According to [here](https://x.org/releases/X11R7.6/doc/xorg-docs/specs/ICCCM/icccm.html), WmState of 3 denotes `IconicState`, or:
> The client's top-level window is iconic (whatever that means for this window manager). The client can assume that its top-level window is not viewable, its icon_window (if any) will be viewable and, failing that, its icon_pixmap (if any) or its WM_ICON_NAME will be displayed.

In notion's case, the window's tab is visible, which seems reasonable to me?  So judging from this trace, I'm thinking maybe this is actually a Java bug.  But if so, it's unclear why it wouldn't happen in Gnome.

**Comment by edmcman** [comment]
Maybe the code that is doing this? https://github.com/openjdk/jdk/blob/04e8cb8641bfdad717b368c087619905bccdf5e6/src/java.desktop/unix/classes/sun/awt/X11/XDropTargetRegistry.java#L66
