### ISSUE TITLE
libextl: extl_stack_get doesn't work for boolean values when ExtlAny is requested

### ISSUE THREAD

**Issue by olejorgenb** [raboof/notion#38]
I'm working on adding icons to tabs and when adding styling support I noticed that `show_icon = true` in a defstyle wasn't retrievable using `grbrush_get_extra`. 

Digging I see that the code initializing the brush extra table  ends up calling `extl_stack_get(st, -1, 'a', FALSE, NULL, &v)` (thorugh `extl_table_iter_do`). Ie. get the stack value as a ExtlAny. But `extl_stack_get` is missing a case when the actual stack type is `LUA_TBOOLEAN`.

It's simple enough to fix:

        case LUA_TBOOLEAN:
            if(type!='b' && type!='a')
                return FALSE;
    
            b=lua_toboolean(st, pos);
    
            if(type=='b'){
                if(valret)
                    *((bool*)valret)=b;
            }else if(type=='a'){
                if(valret){
                    ((ExtlAny*)valret)->type='b';
                    ((ExtlAny*)valret)->value.b=b;
                }
            }
            return TRUE;

I assume this case simply was forgotten (or maybe ExtlAny didn't support boolean at some point). Correct if there's an actual reason for the omission.

**If** I complete the icon branch **and** it's accepted, the fix will be included there. Otherwise the bug's at least exposed here :)

**Comment by raboof** [comment]
I'm not aware of any reason for the omission, thanks for recording the situation here!

**Comment by knixeur** [comment]
This was fixed by merging #79 thanks @olejorgenb !
