### ISSUE TITLE
libextl won't compile with lua5.3 - change in lua_sethook signature.

### ISSUE THREAD

**Issue by jsbackus** [raboof/notion#4]
The signature for lua_sethook has changed in Lua 5.3 and no longer returns a value. Since lua_sethook is now a void, libextl no longer compiles.

**Comment by raboof** [comment]
Interestingly, this function always returned '1', at least since 5.0.3 (http://www.lua.org/source/5.0/ldebug.c.html)

**Comment by jsbackus** [comment]
From what I was able to gather, I don't think it has returned anything useful for a while. Looks like I may have chosen the wrong value... :smile: My fix worked, so I wonder if it is ever checked?

**Comment by raboof** [comment]
Indeed it doesn't appear so - just removed the return value entirely :)

**Comment by jsbackus** [comment]
Even better! Clearly if it compiled w/o a problem then it wasn't used. :smile: The good news is that it otherwise compiled fine under gcc 5, which has been quite a problem for some packages. Then again, it doesn't sound like C got much love in 5...
