### ISSUE TITLE
FreeBSD Port

### ISSUE THREAD

**Issue by xkpd3** [raboof/notion#48]
Hello,

it looks like @AMDmi3 does not support the FreeBSD port for notion anymore.
I found a port (his?) and updated it to the latest notion version.

[ link removed ]

Feel free to link the website to it.

Best Regards,
Stefan

EDIT: AMDmi3 has renamed the repository. The notion port is now here:
https://github.com/AMDmi3/freebsd-ports-wip/tree/master/x11-wm/notion

**Comment by AMDmi3** [comment]
How come I do not? I was planning to update the port, it's just that I'm on vacation now.

**Comment by xkpd3** [comment]
@AMDmi3: Oh ;) Hi! It is not on your github anymore and also not in the ports tree.

Well, I don't want to step on your toe. Feel free to push it online again.

**Comment by xkpd3** [comment]
Ah, the repository has been renamed. Weird, that the github search didn't find it.

@AMDmi3 I found it now... [here](https://github.com/AMDmi3/freebsd-ports-wip/tree/master/x11-wm/notion).

Sorry for the noise.

**Comment by ideasman42** [comment]
There aren't so many changes, couldn't the BSD's be supported be merged upstream? (using some OS checks)

**Comment by xkpd3** [comment]
The license allows changes to make the software work on a given platform.

Also, by renaming the application and executable, even functional modifications are allowed.

I don't really see a problem with sending the port upstream.

**Comment by xkpd3** [comment]
Oh sorry, I read too fast.

Yes, direct upstream support would be nice as well.

**Comment by xkpd3** [comment]
I'm closing this after 1y of inactivity.
