### ISSUE TITLE
New "display dialog as float" feature : problem with scratchpad and option to deactivate

### ISSUE THREAD

**Issue by vincentvidal** [raboof/notion#61]
I have two problems with the new "display dialogs as float" feature:

- the option  "window_dialog_float=false," in etc/cfg_notion.lua does not seem to deactivate dialogs as float.
- when a dialog is opened through a window in the scratchpad, the dialog window appears *under* the scratchpad.

**Comment by vincentvidal** [comment]
I there anybody out there ? ;-)

**Comment by raboof** [comment]
Yes, but I'm not using this feature myself. Perhaps @ideasman42 has any idea since he introduced the feature in 15c73c3ec?

**Comment by vincentvidal** [comment]
Well, as there are some problems with scratchpad, I do not want to use it yet... but cannot disable it with the option window_dialog_float=false. Do you manage to disable this feature ? (without hacking the code, which I finally made..)

**Comment by raboof** [comment]
I don't use the scratchpad myself either, so perhaps I just didn't notice the problems. If you have a clear idea on how to improve this feature that's of course warmly appreciated, with feedback from @ideasman42

**Comment by vincentvidal** [comment]
Well to disable the option I just changed line 232 of file group-ws.c from 

 if(cwin->region.flags&REGION_PLEASE_FLOAT){

to 

 if(cwin->region.flags&REGION_PLEASE_FLOAT && ioncore_g.window_dialog_float){

and it seems to do the trick, but too quick and dirty hack... @ideasman42 has probably a much better solution. The problem of bad interaction with the scratchpad remains the same.

**Comment by torkus** [comment]
hi guys, I've been using ion3/notion for the longest time and its behaviour has been stable and unchanging most of that time.

I was really surprised when I started seeing dialogues floating around.

I'm not sure what is meant by 'scratchpad' (is it the central floating window you can toggle?) but I have both of these problems as well for a while now and they haven't been fixed.

Can the feature be reverted or the bug addressed, please?

Thank you from the bottom of my heart for `notion`.

**Comment by vincentvidal** [comment]
Hi. Yes the scratchpad is the central floating window, where I constantly have an opened mutt terminal, firefox, ... It's a must have for me ;-)
I'm still using the quick and dirty hack mentioned above, which perfectly works for me, and a better solution is still awaited...

**Comment by knixeur** [comment]
Looking at the changes done in 15c73c3 and the current source code, probably what you suggested @vincentvidal is correct. Would you mind to do a PR so we can discuss/test it and fix it?
Thanks!

**Comment by vincentvidal** [comment]
Since more than 15 years that I use ion3/notion, yes, I can take a bit of my time to make a small contribution ;-)
After looking a bit more, I think maybe the best place to test ioncore_g.window_dialog_float would be in ioncore/clientwin.c, line 364 (which is in the commit @knixeur refers to):

    if(netwm_window_type(cwin)==netwm_window_type_get_atom_dialog()){
        cwin->region.flags|=REGION_PLEASE_FLOAT;
    }
should be

    if(ioncore_g.window_dialog_float && netwm_window_type(cwin)==netwm_window_type_get_atom_dialog()){
        cwin->region.flags|=REGION_PLEASE_FLOAT;
    }
REGION_PLEASE_FLOAT is actually used in only one place so the effect would be the same, but if I understand well, REGION_PLEASE_FLOAT should be set only if window_dialog_float is true ?

**Comment by vincentvidal** [comment]
https://github.com/raboof/notion/pull/248
