### ISSUE TITLE
Polybar, and general Notion configuration

### ISSUE THREAD

**Issue by Qwerty-Space** [raboof/notion#68]
Is it possible to configure polybar to work with Notion?  I've done some research and can't seem to find anything

**Comment by raboof** [comment]
I'm not familiar with the project, but have you tried using it with mod_dock? That works with most 3rd party status bars. I'd be curious to hear!

**Comment by Qwerty-Space** [comment]
Sorry, I have no idea how I'd do that.  Would you point me in the right direction please?

**Comment by raboof** [comment]
Sure! Some background is at http://notion.sourceforge.net/notionconf/node4.html#SECTION00410000000000000000. Basically you copy /usr/local/etc/notion/cfg_defaults.lua to ~/.notion/cfg_defaults.lua to be able to tweak it, comment out `dopath("mod_statusbar")` and introduce `dopath("mod_dock")` instead. You may want to also copy and tweak `cfg_dock.lua`. Then just start the statusbar after starting notion. Does that help?

**Comment by Qwerty-Space** [comment]
Thanks.
Is there any documentation for the dock configuration file?

**Comment by raboof** [comment]
Cool! Could you provide any recommendations on what we could improve in our documentation to make this more obvious?

**Comment by Qwerty-Space** [comment]
Maybe mention that `is_dockapp` is provided by the EWMH spec, so it should automatically load to the dock.  And more information on what embedded and floating docks are, with screenshot examples.

At the moment it's quite hard to find things in the documentation, and even then it doesn't seem that clear.  A wiki might be better.

If I have a better way to contact you, I could message you about anything I find unclear when I come across it.

**Comment by wilhelmy** [comment]
hmm.. I wonder how much effort it would be to add support for notion workspaces to polybar, similar to what it seems to have for i3 and bspwm.

**Comment by raboof** [comment]
Might be interesting to track this as a separate issue. It probably reads some EWMH properties for that? It's been a while since I looked into that, but I vaguely remember this was a little tricky to fit in because Notion has workspaces per screen (which I really like) instead of workspaces spanning the screens (which IIRC EWMH is geared towards). I could be misremembering, though.

**Comment by Qwerty-Space** [comment]
> perhaps by adding a README to mod_dock like we do for mod_xrandr?

Yes, that sounds good!!

> I think github issues are the easiest to keep track of things.

Fair enough

**Comment by Qwerty-Space** [comment]
> At the moment it's quite hard to find things in the documentation

For example, is autostarting applications documented anywhere?  [Like in i3](https://i3wm.org/docs/userguide.html#_automatically_starting_applications_on_i3_startup).  I found `ioncore.exec_on()`, but I don't know where I should put that to start polybar after Notion starts.  

The good thing about a wiki is that you can search every page at once, and create pages for rather specific situations (see arch wiki).

**Comment by raboof** [comment]
> > perhaps by adding a README to mod_dock like we do for mod_xrandr?
> 
> Yes, that sounds good!!

Would you want to take a crack at PR'ing? :angel:

**Comment by raboof** [comment]
> > At the moment it's quite hard to find things in the documentation
> 
> For example, is autostarting applications documented anywhere? [Like in i3](https://i3wm.org/docs/userguide.html#_automatically_starting_applications_on_i3_startup). I found `ioncore.exec_on()`

I'm not sure it should even be the responsibility of the windowmanager to start applications on startup - shouldn't that be on whatever also starts the windowmanager? I start my statusbar from my ~/.Xsession, for example. Nonetheless it would of course be helpful to explain this somewhere and give pointers to different ways of achieving that.

> I don't know where I should put that to start polybar after Notion starts.

I think you could just put that in your main `cfg_notion.lua` (http://notion.sourceforge.net/notionconf/node4.html#SECTION00400000000000000000)

**Comment by Qwerty-Space** [comment]
> > > perhaps by adding a README to mod_dock like we do for mod_xrandr?
> > 
> > 
> > Yes, that sounds good!!
> 
> Would you want to take a crack at PR'ing? angel

I might, but I don't think I'm very good at explaining things.
I also have to finish setting up Notion first lol

---

> > > At the moment it's quite hard to find things in the documentation
> > 
> > 
> > For example, is autostarting applications documented anywhere? [Like in i3](https://i3wm.org/docs/userguide.html#_automatically_starting_applications_on_i3_startup). I found `ioncore.exec_on()`
> 
> I'm not sure it should even be the responsibility of the windowmanager to start applications on startup - shouldn't that be on whatever also starts the windowmanager? I start my statusbar from my ~/.Xsession, for example. Nonetheless it would of course be helpful to explain this somewhere and give pointers to different ways of achieving that.
> 
> > I don't know where I should put that to start polybar after Notion starts.
> 
> I think you could just put that in your main `cfg_notion.lua` (http://notion.sourceforge.net/notionconf/node4.html#SECTION00400000000000000000)

Hmm, I'll look into using .Xsession.  Thank you.

**Comment by raboof** [comment]
> I also have to finish setting up Notion first lol

:smile: 

> Hmm, I'll look into using .Xsession. Thank you.

It is probably a bit 'old-fashioned', but it works for me and it's the reason I haven't taken the time to find out how this would work on more 'modern' systems. Perhaps more 'modern' systems just make this the responsibility of the windowmanager and we should add/document this feature, but I'm not sure.

**Comment by Qwerty-Space** [comment]
>Perhaps more 'modern' systems just make this the responsibility of the windowmanager and we should add/document this feature, but I'm not sure.

Most seem to.  i3, and xfce for example.
I believe xfce has an autostart directory, and i3 just has a configuration file for it.

On a semi-related note; how do you change the wallpaper in Notion?

**Comment by raboof** [comment]
Might be good to start separate tickets for separate topics ;)

> On a semi-related note; how do you change the wallpaper in Notion?

You mean for 'floating' workspaces? I don't think Notion has anything specific for setting the background, it just relies on X11 for that. This means it will typically 'inherit' the background already set by your login manager, but you can update it with apps like `xsetroot` (e.g. `xsetroot -solid blue`) - I'm sure there are others. One thing I noticed is that the new background doesn't take effect until it is redrawn - so you might need to switch workspaces or move your window around to see it.

This is possibly a bug - perhaps the WM is notified of the background change and it is up to the WM to trigger the repaint? Not sure.

**Comment by Qwerty-Space** [comment]
>You mean for 'floating' workspaces?
Hey, some people like transparent windows for their TWM ;-P
>but you can update it with apps like xsetroot (e.g. xsetroot -solid blue) - I'm sure there are others. One thing I noticed is that the new background doesn't take effect until it is redrawn - so you might need to switch workspaces or move your window around to see it.
Hmm, I tried using `feh` to set the background, but that didn't seem to do anything.
And yeah, it should probably be up to the WM to trigger the repaint.  Since some people might have wallpaper slideshows or something

**Comment by raboof** [comment]
> > You mean for 'floating' workspaces?
> 
> Hey, some people like transparent windows for their TWM ;-P

Sure! I was just asking for clarification, no judgement ;).

> Hmm, I tried using `feh` to set the background, but that didn't seem to do anything.

`feh --bg-fill /some/image` worked for me for a 'floating' workspace (with the caveat already mentioned above that it needs a nudge to redraw). Indeed on tiling workspaces I don't see the background image. I suspect Notion is drawing black squares over it on the tabs. I'm not sure if that's accurate and how easy it would be to make those transparent instead, though.

**Comment by dalaidakkar** [comment]
You can set transparent background for tiled workspaces in the theme file of the theme you are using for example mine is  ~/.notion/look_greenlight2.lua
and I have this line:

de.defstyle("frame", {
    background_colour = "#000000",
    transparent_background = true,
})

**Comment by dalaidakkar** [comment]
I attach my 2 favorite customized theme files in case you want to try them.

[myfav_themes.zip](https://github.com/raboof/notion/files/2798367/myfav_themes.zip)

**Comment by Qwerty-Space** [comment]
> > > You mean for 'floating' workspaces?
> > 
> > 
> > Hey, some people like transparent windows for their TWM ;-P
> 
> Sure! I was just asking for clarification, no judgement ;).
> 
> > Hmm, I tried using `feh` to set the background, but that didn't seem to do anything.
> 
> `feh --bg-fill /some/image` worked for me for a 'floating' workspace (with the caveat already mentioned above that it needs a nudge to redraw). Indeed on tiling workspaces I don't see the background image. I suspect Notion is drawing black squares over it on the tabs. I'm not sure if that's accurate and how easy it would be to make those transparent instead, though.

It was because I needed to change my look.lua.
