### ISSUE TITLE
Change license to LGPL

### ISSUE THREAD

**Issue by raboof** [raboof/notion#88]
td;dr: Notion is currently released under the "Ion License", which is the LGPL with a slight (trademark-ish) amendment. For this to happen we would have to re-implement some features that are currently only available under the Ion License and for which the original author is not inclined to allow distribution under the plain LGPL.

# Background

Notion is a fork of Ion, created when the original Ion maintainer retired the project.

Before 2007, Ion was licensed under the LGPL. In 2007, a "Name policy" was added, which introduced some additional restrictions when releasing the code under a name that is associated with the Ion project. It is unclear whether this should be read as an integral part of the license, or as a trademark provision. Even though Notion is clearly not associated with the original Ion project, so the restrictions from the name policy do not apply to Notion, it makes it unclear whether Notion is strictly spoken "non-free".

In 2010, the original author abandoned the Ion project, and Notion was created. It has been a long-standing wish for the Notion project to move back to the plain LGPL. Unfortunately reaching out to the original author to relicense his contributions since 2007 was not succesful. All contributions to Notion since 2010, however, have been explicitly dual-licensed under the Ion license *and* the LGPL.

# Approach

We would like to achieve a version of Notion that removes the confusion of the "name policy" and is clearly licensed under the plain LGPL. For this we can use all code prior to 2007 and after the forking of Notion, but not any code that has been introduced between those 2 points.

At the same time, however, we want to allow contributions to the 'master' branch, and be able to pull those contributions into the LGPL 

To achieve that, we have introduced an 'lgpl' branch to Notion, which is intended to contain only LGPL code. To achieve this, we have taken the code up to the license change, and then did a "merge" of the non-LGPL git tree with the "ours" merge strategy. This exotic merge strategy (not to be confused with the "ours" merge strategy _option_) disregards all code from the non-LGPL branch, but does add them to the git history of the branch. This means from that point on, we can merge from `master` into `lgpl` without 'leaking' non-LGPL code into the LGPL branch. This still involves careful manual work, and is a work-in-progress I have been working on. I would like to do the merging myself, but testing this branch and proposing fixes (while being careful not to violate any copyrights by copying code that is only available under the Ion license) would be very helpful.

## List of features to be backported.

A possibly-outdated list of features to be reimplemented can be found at https://sourceforge.net/p/notion/lgpl-regressions/search/?q=%21status%3Awont-fix+%26%26+%21status%3Aclosed . Once the `lgpl` branch is up-to-date with master again we should verify them and if valid move them to the GitHub issue tracker.

**Comment by raboof** [comment]
The last remaining task is to rename the current `master` to `notion-3` and rename the `lgpl` branch to `master`.

We want to do this when we have solved all serious regressions [tracked with the LGPL label](https://github.com/raboof/notion/issues?q=is%3Aopen+is%3Aissue+label%3ALGPL)

**Comment by wilhelmy** [comment]
I know it's unlikely to be successful, but have you contacted tuomov? Maybe he stopped caring after all this time.

**Comment by raboof** [comment]
I have unsuccessfully tried that in the past and am not planning to try again.

**Comment by raboof** [comment]
> The last remaining task is to rename the current master to notion-3 and rename the lgpl branch to master.
>
> We want to do this when we have solved all serious regressions tracked with the LGPL label

Done! :tada:
