### ISSUE TITLE
Use pkg-config for all library stuff

### ISSUE THREAD

**Issue by xmw** [raboof/notion#9]
Hi,
I took a look at the updated Gentoo package and wrote a patch [1] to use pkg-config for all library flags.
It would be nice to have on installations with awkward library location in general, i.e. Gentoo/Prefix.
Thanks
[1] https://sources.gentoo.org/cgi-bin/viewvc.cgi/gentoo-x86/x11-wm/notion/files/notion-3_p2015061300-pkg-config.patch?view=markup

**Comment by raboof** [comment]
Should now be fixed via #13 , thanks for your report and patch (and thanks to @knixeur for the PR :) )
