### ISSUE TITLE
Make sf.net redirect to notionwm.net

### ISSUE THREAD

**Issue by raboof** [raboof/notion#92]
http://notion.sourceforge.net should redirect to https://notionwm.net

**Comment by raboof** [comment]
implemented https://sourceforge.net/p/forge/documentation/Project%20Web%20Services/#re-directing-to-another-site for the home page

**Comment by knixeur** [comment]
Please, use a 301 redirect (permanent) so index engines will start indexing it correctly.
```
header("Location: https://notionwm.net", TRUE, 301);
```
Thanks!

**Comment by raboof** [comment]
:+1: done!
