### ISSUE TITLE
Custom styles need explicit 'based-on' to inherit default values

### ISSUE THREAD

**Issue by raboof** [raboof/notion#94]
I have a customer 'look' that was made for `master`.

On the `lgpl` branch, inactive tabs have a black background instead of my configured background color.

**Comment by raboof** [comment]
My custom style for `"tab"` was missing a `based_on = "*"`, which used to be needed but which was lifted at some point.

The built-in styles seem OK. I'm not convinced we should re-implement removing the need for `based_on`, I think we should rather make a note in any migration notes.

**Comment by knixeur** [comment]
Mmm what about based_on = "*" being the default value? It would just be overwritten by the look if defined.

**Comment by raboof** [comment]
Sounds reasonable but doesn't feel like a blocker for Notion 4 - let's keep the issue open as 'enhancement' and remove it from the Notion 4 board.

**Comment by wilhelmy** [comment]
Can this be closed?

**Comment by raboof** [comment]
good one, missed that
