### ISSUE TITLE
Unable to reparent in unsqueeze

### ISSUE THREAD

**Issue by knixeur** [raboof/notion#99]
This happens when the current frame is too narrow (small width) and you press F9 to popup new workspace query. It tries to unsqueeze so everything can be read but it fails.
It probably happens with any other query, but create workspace has a long text by default so it's easier to see.
```
/usr/local/bin/notion: Unable to reparent.
/usr/local/bin/notion: Stack trace:
0 [C]: in 'unsqueeze'
1 mod_query.lua:80: in 'query'
2 mod_query.lua:545: in 'query_workspace'
3 [string "mod_query.query_workspace(_)"]:1
  [Skipping unnamed C functions.]
```

**Comment by raboof** [comment]
Hmm I can't seem to reproduce this - for me 'unsqueeze' is indeed called and determines the region is smaller than the minimum size, but detach appears to work and the mod_query is put on the parent (wscreen?) instead. perhaps due to the extensions I have (or have not) loaded?

**Comment by knixeur** [comment]
I've been testing with a clean repo/config using docker and xephyr so no weird stuff should be affecting it.
The frame most be focused (if it's not it doesn't need to reparent as the screen is wider) and has to be smaller in width than the displayed text in the query, I could even reproduce it with the Run query.
I'll upload a small image soon.

**Comment by raboof** [comment]
I believe you :smile: just didn't see it myself yet. Will try enabling/disabling xrandr/xinerama later this weekend, feels like that might be related.

**Comment by knixeur** [comment]
No problem, I'm attaching the gif, I've tried disabling xinerama/randr in Xepyhr but I get the same result.

![Peek 2019-05-10 12-28](https://user-images.githubusercontent.com/1289632/57538786-8390dc00-731f-11e9-976f-d4802aa373c4.gif)

Dockerfile just in case

```
# Xephyr :1 -ac -br -screen 1024x768 +xinerama +extension RANDR -resizeable -reset
# docker build -f ./Dockerfile ./notion -t notion && docker run --rm -it -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix notion
# docker build -f ./Dockerfile ./notion -t notion && docker run --rm -it -e DISPLAY=:1 -v /tmp/.X11-unix:/tmp/.X11-unix --entrypoint /bin/bash notion
FROM ubuntu:18.04
ENV DEBIAN_FRONTEND=noninteractive
RUN apt update && apt install -y pkg-config build-essential
RUN apt update && apt install -y libx11-dev libxext-dev libsm-dev libxinerama-dev libxrandr-dev gettext x11-utils \
 xterm x11-xserver-utils wget unzip xserver-xorg-video-dummy
RUN apt update && apt install -y lua5.2 liblua5.2-dev
RUN mkdir /notion
WORKDIR /notion
COPY . /notion/
RUN make && make install
ENTRYPOINT ["/usr/local/bin/notion"]
```
